-- MySQL Script generated by MySQL Workbench
-- Fri May  9 17:10:27 2025
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema recursos_humanos
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema recursos_humanos
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `recursos_humanos` DEFAULT CHARACTER SET utf8 ;
USE `recursos_humanos` ;

-- -----------------------------------------------------
-- Table `recursos_humanos`.`funcionario`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `recursos_humanos`.`funcionario` ;

CREATE TABLE IF NOT EXISTS `recursos_humanos`.`funcionario` (
  `id_funcionario` INT NOT NULL AUTO_INCREMENT,
  `tipo_identificacion` VARCHAR(50) NOT NULL,
  `numero_identificacion` VARCHAR(100) NOT NULL,
  `nombres` VARCHAR(100) NOT NULL,
  `apellidos` VARCHAR(100) NOT NULL,
  `estado_civil` VARCHAR(50) NULL,
  `sexo` VARCHAR(45) NULL,
  `direccion` VARCHAR(150) NULL,
  `telefono` VARCHAR(45) NULL,
  `fecha_nacimiento` DATE NULL,
  PRIMARY KEY (`id_funcionario`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `recursos_humanos`.`grupo_familiar`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `recursos_humanos`.`grupo_familiar` ;

CREATE TABLE IF NOT EXISTS `recursos_humanos`.`grupo_familiar` (
  `id_familiar` INT NOT NULL AUTO_INCREMENT,
  `nombres` VARCHAR(100) NOT NULL,
  `apellidos` VARCHAR(100) NOT NULL,
  `parentesco` VARCHAR(45) NOT NULL,
  `fecha_nacimiento` DATE NULL,
  `id_funcionario` INT NOT NULL,
  PRIMARY KEY (`id_familiar`),
  CONSTRAINT `fk_grupo_familiar_funcionario1`
    FOREIGN KEY (`id_funcionario`)
    REFERENCES `recursos_humanos`.`funcionario` (`id_funcionario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_grupo_familiar_funcionario1_idx` ON `recursos_humanos`.`grupo_familiar` (`id_funcionario` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `recursos_humanos`.`informacion_academica`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `recursos_humanos`.`informacion_academica` ;

CREATE TABLE IF NOT EXISTS `recursos_humanos`.`informacion_academica` (
  `id_academico` INT NOT NULL AUTO_INCREMENT,
  `universidad` VARCHAR(100) NOT NULL,
  `nivel_estudio` VARCHAR(45) NULL,
  `titulo` VARCHAR(100) NULL,
  `id_funcionario` INT NOT NULL,
  PRIMARY KEY (`id_academico`),
  CONSTRAINT `fk_informacion_academica_funcionario1`
    FOREIGN KEY (`id_funcionario`)
    REFERENCES `recursos_humanos`.`funcionario` (`id_funcionario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_informacion_academica_funcionario1_idx` ON `recursos_humanos`.`informacion_academica` (`id_funcionario` ASC) VISIBLE;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
